export var bean = "toast";
// => var bean = module.exports.bean = ...

export let that = "that";
// => let that = module.exports.that = ...

export const thing = "thing";
// => const thing = module.exports.thing = ...

// *
export function boobs() {};
// let boobs = module.exports.boobs = function boobs...

export class Woman extends Object {};
// let Woman = module.exports.Woman = class Woman extends Object {...

// export default "yo" // <- don't think we gotta do anything. Take at face value.
// module.default = ...

export default class Wife extends Woman {};
// let Wife = module.default = class Wife extends Woman {...